
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `School` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model School
 * 
 */
export type SchoolModel = runtime.Types.Result.DefaultSelection<Prisma.$SchoolPayload>

export type AggregateSchool = {
  _count: SchoolCountAggregateOutputType | null
  _min: SchoolMinAggregateOutputType | null
  _max: SchoolMaxAggregateOutputType | null
}

export type SchoolMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  phoneNumber: string | null
  address: string | null
  type: string | null
  code: string | null
  image: string | null
  status: string | null
  createdAt: Date | null
}

export type SchoolMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  phoneNumber: string | null
  address: string | null
  type: string | null
  code: string | null
  image: string | null
  status: string | null
  createdAt: Date | null
}

export type SchoolCountAggregateOutputType = {
  id: number
  name: number
  email: number
  phoneNumber: number
  address: number
  type: number
  code: number
  image: number
  status: number
  createdAt: number
  schoolAdmins: number
  _all: number
}


export type SchoolMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phoneNumber?: true
  address?: true
  type?: true
  code?: true
  image?: true
  status?: true
  createdAt?: true
}

export type SchoolMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phoneNumber?: true
  address?: true
  type?: true
  code?: true
  image?: true
  status?: true
  createdAt?: true
}

export type SchoolCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phoneNumber?: true
  address?: true
  type?: true
  code?: true
  image?: true
  status?: true
  createdAt?: true
  schoolAdmins?: true
  _all?: true
}

export type SchoolAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which School to aggregate.
   */
  where?: Prisma.SchoolWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Schools to fetch.
   */
  orderBy?: Prisma.SchoolOrderByWithRelationInput | Prisma.SchoolOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SchoolWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Schools from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Schools.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Schools
  **/
  _count?: true | SchoolCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SchoolMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SchoolMaxAggregateInputType
}

export type GetSchoolAggregateType<T extends SchoolAggregateArgs> = {
      [P in keyof T & keyof AggregateSchool]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSchool[P]>
    : Prisma.GetScalarType<T[P], AggregateSchool[P]>
}




export type SchoolGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SchoolWhereInput
  orderBy?: Prisma.SchoolOrderByWithAggregationInput | Prisma.SchoolOrderByWithAggregationInput[]
  by: Prisma.SchoolScalarFieldEnum[] | Prisma.SchoolScalarFieldEnum
  having?: Prisma.SchoolScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SchoolCountAggregateInputType | true
  _min?: SchoolMinAggregateInputType
  _max?: SchoolMaxAggregateInputType
}

export type SchoolGroupByOutputType = {
  id: string
  name: string
  email: string
  phoneNumber: string
  address: string
  type: string
  code: string
  image: string
  status: string
  createdAt: Date
  schoolAdmins: string[]
  _count: SchoolCountAggregateOutputType | null
  _min: SchoolMinAggregateOutputType | null
  _max: SchoolMaxAggregateOutputType | null
}

type GetSchoolGroupByPayload<T extends SchoolGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SchoolGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SchoolGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SchoolGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SchoolGroupByOutputType[P]>
      }
    >
  >



export type SchoolWhereInput = {
  AND?: Prisma.SchoolWhereInput | Prisma.SchoolWhereInput[]
  OR?: Prisma.SchoolWhereInput[]
  NOT?: Prisma.SchoolWhereInput | Prisma.SchoolWhereInput[]
  id?: Prisma.StringFilter<"School"> | string
  name?: Prisma.StringFilter<"School"> | string
  email?: Prisma.StringFilter<"School"> | string
  phoneNumber?: Prisma.StringFilter<"School"> | string
  address?: Prisma.StringFilter<"School"> | string
  type?: Prisma.StringFilter<"School"> | string
  code?: Prisma.StringFilter<"School"> | string
  image?: Prisma.StringFilter<"School"> | string
  status?: Prisma.StringFilter<"School"> | string
  createdAt?: Prisma.DateTimeFilter<"School"> | Date | string
  schoolAdmins?: Prisma.StringNullableListFilter<"School">
  schoolDetails?: Prisma.XOR<Prisma.SchoolDetailsNullableScalarRelationFilter, Prisma.SchoolDetailsWhereInput> | null
}

export type SchoolOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  address?: Prisma.SortOrder
  type?: Prisma.SortOrder
  code?: Prisma.SortOrder
  image?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  schoolAdmins?: Prisma.SortOrder
  schoolDetails?: Prisma.SchoolDetailsOrderByWithRelationInput
}

export type SchoolWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SchoolWhereInput | Prisma.SchoolWhereInput[]
  OR?: Prisma.SchoolWhereInput[]
  NOT?: Prisma.SchoolWhereInput | Prisma.SchoolWhereInput[]
  name?: Prisma.StringFilter<"School"> | string
  email?: Prisma.StringFilter<"School"> | string
  phoneNumber?: Prisma.StringFilter<"School"> | string
  address?: Prisma.StringFilter<"School"> | string
  type?: Prisma.StringFilter<"School"> | string
  code?: Prisma.StringFilter<"School"> | string
  image?: Prisma.StringFilter<"School"> | string
  status?: Prisma.StringFilter<"School"> | string
  createdAt?: Prisma.DateTimeFilter<"School"> | Date | string
  schoolAdmins?: Prisma.StringNullableListFilter<"School">
  schoolDetails?: Prisma.XOR<Prisma.SchoolDetailsNullableScalarRelationFilter, Prisma.SchoolDetailsWhereInput> | null
}, "id">

export type SchoolOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  address?: Prisma.SortOrder
  type?: Prisma.SortOrder
  code?: Prisma.SortOrder
  image?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  schoolAdmins?: Prisma.SortOrder
  _count?: Prisma.SchoolCountOrderByAggregateInput
  _max?: Prisma.SchoolMaxOrderByAggregateInput
  _min?: Prisma.SchoolMinOrderByAggregateInput
}

export type SchoolScalarWhereWithAggregatesInput = {
  AND?: Prisma.SchoolScalarWhereWithAggregatesInput | Prisma.SchoolScalarWhereWithAggregatesInput[]
  OR?: Prisma.SchoolScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SchoolScalarWhereWithAggregatesInput | Prisma.SchoolScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"School"> | string
  name?: Prisma.StringWithAggregatesFilter<"School"> | string
  email?: Prisma.StringWithAggregatesFilter<"School"> | string
  phoneNumber?: Prisma.StringWithAggregatesFilter<"School"> | string
  address?: Prisma.StringWithAggregatesFilter<"School"> | string
  type?: Prisma.StringWithAggregatesFilter<"School"> | string
  code?: Prisma.StringWithAggregatesFilter<"School"> | string
  image?: Prisma.StringWithAggregatesFilter<"School"> | string
  status?: Prisma.StringWithAggregatesFilter<"School"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"School"> | Date | string
  schoolAdmins?: Prisma.StringNullableListFilter<"School">
}

export type SchoolCreateInput = {
  id?: string
  name: string
  email: string
  phoneNumber: string
  address?: string
  type: string
  code: string
  image?: string
  status?: string
  createdAt?: Date | string
  schoolAdmins?: Prisma.SchoolCreateschoolAdminsInput | string[]
  schoolDetails?: Prisma.SchoolDetailsCreateNestedOneWithoutSchoolInput
}

export type SchoolUncheckedCreateInput = {
  id?: string
  name: string
  email: string
  phoneNumber: string
  address?: string
  type: string
  code: string
  image?: string
  status?: string
  createdAt?: Date | string
  schoolAdmins?: Prisma.SchoolCreateschoolAdminsInput | string[]
  schoolDetails?: Prisma.SchoolDetailsUncheckedCreateNestedOneWithoutSchoolInput
}

export type SchoolUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  schoolAdmins?: Prisma.SchoolUpdateschoolAdminsInput | string[]
  schoolDetails?: Prisma.SchoolDetailsUpdateOneWithoutSchoolNestedInput
}

export type SchoolUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  schoolAdmins?: Prisma.SchoolUpdateschoolAdminsInput | string[]
  schoolDetails?: Prisma.SchoolDetailsUncheckedUpdateOneWithoutSchoolNestedInput
}

export type SchoolCreateManyInput = {
  id?: string
  name: string
  email: string
  phoneNumber: string
  address?: string
  type: string
  code: string
  image?: string
  status?: string
  createdAt?: Date | string
  schoolAdmins?: Prisma.SchoolCreateschoolAdminsInput | string[]
}

export type SchoolUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  schoolAdmins?: Prisma.SchoolUpdateschoolAdminsInput | string[]
}

export type SchoolUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  schoolAdmins?: Prisma.SchoolUpdateschoolAdminsInput | string[]
}

export type SchoolCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  address?: Prisma.SortOrder
  type?: Prisma.SortOrder
  code?: Prisma.SortOrder
  image?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  schoolAdmins?: Prisma.SortOrder
}

export type SchoolMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  address?: Prisma.SortOrder
  type?: Prisma.SortOrder
  code?: Prisma.SortOrder
  image?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SchoolMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  address?: Prisma.SortOrder
  type?: Prisma.SortOrder
  code?: Prisma.SortOrder
  image?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SchoolScalarRelationFilter = {
  is?: Prisma.SchoolWhereInput
  isNot?: Prisma.SchoolWhereInput
}

export type SchoolCreateschoolAdminsInput = {
  set: string[]
}

export type SchoolUpdateschoolAdminsInput = {
  set?: string[]
  push?: string | string[]
}

export type SchoolCreateNestedOneWithoutSchoolDetailsInput = {
  create?: Prisma.XOR<Prisma.SchoolCreateWithoutSchoolDetailsInput, Prisma.SchoolUncheckedCreateWithoutSchoolDetailsInput>
  connectOrCreate?: Prisma.SchoolCreateOrConnectWithoutSchoolDetailsInput
  connect?: Prisma.SchoolWhereUniqueInput
}

export type SchoolUpdateOneRequiredWithoutSchoolDetailsNestedInput = {
  create?: Prisma.XOR<Prisma.SchoolCreateWithoutSchoolDetailsInput, Prisma.SchoolUncheckedCreateWithoutSchoolDetailsInput>
  connectOrCreate?: Prisma.SchoolCreateOrConnectWithoutSchoolDetailsInput
  upsert?: Prisma.SchoolUpsertWithoutSchoolDetailsInput
  connect?: Prisma.SchoolWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SchoolUpdateToOneWithWhereWithoutSchoolDetailsInput, Prisma.SchoolUpdateWithoutSchoolDetailsInput>, Prisma.SchoolUncheckedUpdateWithoutSchoolDetailsInput>
}

export type SchoolCreateWithoutSchoolDetailsInput = {
  id?: string
  name: string
  email: string
  phoneNumber: string
  address?: string
  type: string
  code: string
  image?: string
  status?: string
  createdAt?: Date | string
  schoolAdmins?: Prisma.SchoolCreateschoolAdminsInput | string[]
}

export type SchoolUncheckedCreateWithoutSchoolDetailsInput = {
  id?: string
  name: string
  email: string
  phoneNumber: string
  address?: string
  type: string
  code: string
  image?: string
  status?: string
  createdAt?: Date | string
  schoolAdmins?: Prisma.SchoolCreateschoolAdminsInput | string[]
}

export type SchoolCreateOrConnectWithoutSchoolDetailsInput = {
  where: Prisma.SchoolWhereUniqueInput
  create: Prisma.XOR<Prisma.SchoolCreateWithoutSchoolDetailsInput, Prisma.SchoolUncheckedCreateWithoutSchoolDetailsInput>
}

export type SchoolUpsertWithoutSchoolDetailsInput = {
  update: Prisma.XOR<Prisma.SchoolUpdateWithoutSchoolDetailsInput, Prisma.SchoolUncheckedUpdateWithoutSchoolDetailsInput>
  create: Prisma.XOR<Prisma.SchoolCreateWithoutSchoolDetailsInput, Prisma.SchoolUncheckedCreateWithoutSchoolDetailsInput>
  where?: Prisma.SchoolWhereInput
}

export type SchoolUpdateToOneWithWhereWithoutSchoolDetailsInput = {
  where?: Prisma.SchoolWhereInput
  data: Prisma.XOR<Prisma.SchoolUpdateWithoutSchoolDetailsInput, Prisma.SchoolUncheckedUpdateWithoutSchoolDetailsInput>
}

export type SchoolUpdateWithoutSchoolDetailsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  schoolAdmins?: Prisma.SchoolUpdateschoolAdminsInput | string[]
}

export type SchoolUncheckedUpdateWithoutSchoolDetailsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  schoolAdmins?: Prisma.SchoolUpdateschoolAdminsInput | string[]
}



export type SchoolSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phoneNumber?: boolean
  address?: boolean
  type?: boolean
  code?: boolean
  image?: boolean
  status?: boolean
  createdAt?: boolean
  schoolAdmins?: boolean
  schoolDetails?: boolean | Prisma.School$schoolDetailsArgs<ExtArgs>
}, ExtArgs["result"]["school"]>

export type SchoolSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phoneNumber?: boolean
  address?: boolean
  type?: boolean
  code?: boolean
  image?: boolean
  status?: boolean
  createdAt?: boolean
  schoolAdmins?: boolean
}, ExtArgs["result"]["school"]>

export type SchoolSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phoneNumber?: boolean
  address?: boolean
  type?: boolean
  code?: boolean
  image?: boolean
  status?: boolean
  createdAt?: boolean
  schoolAdmins?: boolean
}, ExtArgs["result"]["school"]>

export type SchoolSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  phoneNumber?: boolean
  address?: boolean
  type?: boolean
  code?: boolean
  image?: boolean
  status?: boolean
  createdAt?: boolean
  schoolAdmins?: boolean
}

export type SchoolOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "phoneNumber" | "address" | "type" | "code" | "image" | "status" | "createdAt" | "schoolAdmins", ExtArgs["result"]["school"]>
export type SchoolInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  schoolDetails?: boolean | Prisma.School$schoolDetailsArgs<ExtArgs>
}
export type SchoolIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SchoolIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SchoolPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "School"
  objects: {
    schoolDetails: Prisma.$SchoolDetailsPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string
    phoneNumber: string
    address: string
    type: string
    code: string
    image: string
    status: string
    createdAt: Date
    schoolAdmins: string[]
  }, ExtArgs["result"]["school"]>
  composites: {}
}

export type SchoolGetPayload<S extends boolean | null | undefined | SchoolDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SchoolPayload, S>

export type SchoolCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SchoolFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SchoolCountAggregateInputType | true
  }

export interface SchoolDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['School'], meta: { name: 'School' } }
  /**
   * Find zero or one School that matches the filter.
   * @param {SchoolFindUniqueArgs} args - Arguments to find a School
   * @example
   * // Get one School
   * const school = await prisma.school.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SchoolFindUniqueArgs>(args: Prisma.SelectSubset<T, SchoolFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SchoolClient<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one School that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SchoolFindUniqueOrThrowArgs} args - Arguments to find a School
   * @example
   * // Get one School
   * const school = await prisma.school.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SchoolFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SchoolFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SchoolClient<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first School that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolFindFirstArgs} args - Arguments to find a School
   * @example
   * // Get one School
   * const school = await prisma.school.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SchoolFindFirstArgs>(args?: Prisma.SelectSubset<T, SchoolFindFirstArgs<ExtArgs>>): Prisma.Prisma__SchoolClient<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first School that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolFindFirstOrThrowArgs} args - Arguments to find a School
   * @example
   * // Get one School
   * const school = await prisma.school.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SchoolFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SchoolFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SchoolClient<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Schools that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Schools
   * const schools = await prisma.school.findMany()
   * 
   * // Get first 10 Schools
   * const schools = await prisma.school.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const schoolWithIdOnly = await prisma.school.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SchoolFindManyArgs>(args?: Prisma.SelectSubset<T, SchoolFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a School.
   * @param {SchoolCreateArgs} args - Arguments to create a School.
   * @example
   * // Create one School
   * const School = await prisma.school.create({
   *   data: {
   *     // ... data to create a School
   *   }
   * })
   * 
   */
  create<T extends SchoolCreateArgs>(args: Prisma.SelectSubset<T, SchoolCreateArgs<ExtArgs>>): Prisma.Prisma__SchoolClient<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Schools.
   * @param {SchoolCreateManyArgs} args - Arguments to create many Schools.
   * @example
   * // Create many Schools
   * const school = await prisma.school.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SchoolCreateManyArgs>(args?: Prisma.SelectSubset<T, SchoolCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Schools and returns the data saved in the database.
   * @param {SchoolCreateManyAndReturnArgs} args - Arguments to create many Schools.
   * @example
   * // Create many Schools
   * const school = await prisma.school.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Schools and only return the `id`
   * const schoolWithIdOnly = await prisma.school.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SchoolCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SchoolCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a School.
   * @param {SchoolDeleteArgs} args - Arguments to delete one School.
   * @example
   * // Delete one School
   * const School = await prisma.school.delete({
   *   where: {
   *     // ... filter to delete one School
   *   }
   * })
   * 
   */
  delete<T extends SchoolDeleteArgs>(args: Prisma.SelectSubset<T, SchoolDeleteArgs<ExtArgs>>): Prisma.Prisma__SchoolClient<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one School.
   * @param {SchoolUpdateArgs} args - Arguments to update one School.
   * @example
   * // Update one School
   * const school = await prisma.school.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SchoolUpdateArgs>(args: Prisma.SelectSubset<T, SchoolUpdateArgs<ExtArgs>>): Prisma.Prisma__SchoolClient<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Schools.
   * @param {SchoolDeleteManyArgs} args - Arguments to filter Schools to delete.
   * @example
   * // Delete a few Schools
   * const { count } = await prisma.school.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SchoolDeleteManyArgs>(args?: Prisma.SelectSubset<T, SchoolDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Schools.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Schools
   * const school = await prisma.school.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SchoolUpdateManyArgs>(args: Prisma.SelectSubset<T, SchoolUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Schools and returns the data updated in the database.
   * @param {SchoolUpdateManyAndReturnArgs} args - Arguments to update many Schools.
   * @example
   * // Update many Schools
   * const school = await prisma.school.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Schools and only return the `id`
   * const schoolWithIdOnly = await prisma.school.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SchoolUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SchoolUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one School.
   * @param {SchoolUpsertArgs} args - Arguments to update or create a School.
   * @example
   * // Update or create a School
   * const school = await prisma.school.upsert({
   *   create: {
   *     // ... data to create a School
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the School we want to update
   *   }
   * })
   */
  upsert<T extends SchoolUpsertArgs>(args: Prisma.SelectSubset<T, SchoolUpsertArgs<ExtArgs>>): Prisma.Prisma__SchoolClient<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Schools.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolCountArgs} args - Arguments to filter Schools to count.
   * @example
   * // Count the number of Schools
   * const count = await prisma.school.count({
   *   where: {
   *     // ... the filter for the Schools we want to count
   *   }
   * })
  **/
  count<T extends SchoolCountArgs>(
    args?: Prisma.Subset<T, SchoolCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SchoolCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a School.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SchoolAggregateArgs>(args: Prisma.Subset<T, SchoolAggregateArgs>): Prisma.PrismaPromise<GetSchoolAggregateType<T>>

  /**
   * Group by School.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SchoolGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SchoolGroupByArgs['orderBy'] }
      : { orderBy?: SchoolGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SchoolGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSchoolGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the School model
 */
readonly fields: SchoolFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for School.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SchoolClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  schoolDetails<T extends Prisma.School$schoolDetailsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.School$schoolDetailsArgs<ExtArgs>>): Prisma.Prisma__SchoolDetailsClient<runtime.Types.Result.GetResult<Prisma.$SchoolDetailsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the School model
 */
export interface SchoolFieldRefs {
  readonly id: Prisma.FieldRef<"School", 'String'>
  readonly name: Prisma.FieldRef<"School", 'String'>
  readonly email: Prisma.FieldRef<"School", 'String'>
  readonly phoneNumber: Prisma.FieldRef<"School", 'String'>
  readonly address: Prisma.FieldRef<"School", 'String'>
  readonly type: Prisma.FieldRef<"School", 'String'>
  readonly code: Prisma.FieldRef<"School", 'String'>
  readonly image: Prisma.FieldRef<"School", 'String'>
  readonly status: Prisma.FieldRef<"School", 'String'>
  readonly createdAt: Prisma.FieldRef<"School", 'DateTime'>
  readonly schoolAdmins: Prisma.FieldRef<"School", 'String[]'>
}
    

// Custom InputTypes
/**
 * School findUnique
 */
export type SchoolFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolInclude<ExtArgs> | null
  /**
   * Filter, which School to fetch.
   */
  where: Prisma.SchoolWhereUniqueInput
}

/**
 * School findUniqueOrThrow
 */
export type SchoolFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolInclude<ExtArgs> | null
  /**
   * Filter, which School to fetch.
   */
  where: Prisma.SchoolWhereUniqueInput
}

/**
 * School findFirst
 */
export type SchoolFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolInclude<ExtArgs> | null
  /**
   * Filter, which School to fetch.
   */
  where?: Prisma.SchoolWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Schools to fetch.
   */
  orderBy?: Prisma.SchoolOrderByWithRelationInput | Prisma.SchoolOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Schools.
   */
  cursor?: Prisma.SchoolWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Schools from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Schools.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Schools.
   */
  distinct?: Prisma.SchoolScalarFieldEnum | Prisma.SchoolScalarFieldEnum[]
}

/**
 * School findFirstOrThrow
 */
export type SchoolFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolInclude<ExtArgs> | null
  /**
   * Filter, which School to fetch.
   */
  where?: Prisma.SchoolWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Schools to fetch.
   */
  orderBy?: Prisma.SchoolOrderByWithRelationInput | Prisma.SchoolOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Schools.
   */
  cursor?: Prisma.SchoolWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Schools from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Schools.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Schools.
   */
  distinct?: Prisma.SchoolScalarFieldEnum | Prisma.SchoolScalarFieldEnum[]
}

/**
 * School findMany
 */
export type SchoolFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolInclude<ExtArgs> | null
  /**
   * Filter, which Schools to fetch.
   */
  where?: Prisma.SchoolWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Schools to fetch.
   */
  orderBy?: Prisma.SchoolOrderByWithRelationInput | Prisma.SchoolOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Schools.
   */
  cursor?: Prisma.SchoolWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Schools from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Schools.
   */
  skip?: number
  distinct?: Prisma.SchoolScalarFieldEnum | Prisma.SchoolScalarFieldEnum[]
}

/**
 * School create
 */
export type SchoolCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolInclude<ExtArgs> | null
  /**
   * The data needed to create a School.
   */
  data: Prisma.XOR<Prisma.SchoolCreateInput, Prisma.SchoolUncheckedCreateInput>
}

/**
 * School createMany
 */
export type SchoolCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Schools.
   */
  data: Prisma.SchoolCreateManyInput | Prisma.SchoolCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * School createManyAndReturn
 */
export type SchoolCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * The data used to create many Schools.
   */
  data: Prisma.SchoolCreateManyInput | Prisma.SchoolCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * School update
 */
export type SchoolUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolInclude<ExtArgs> | null
  /**
   * The data needed to update a School.
   */
  data: Prisma.XOR<Prisma.SchoolUpdateInput, Prisma.SchoolUncheckedUpdateInput>
  /**
   * Choose, which School to update.
   */
  where: Prisma.SchoolWhereUniqueInput
}

/**
 * School updateMany
 */
export type SchoolUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Schools.
   */
  data: Prisma.XOR<Prisma.SchoolUpdateManyMutationInput, Prisma.SchoolUncheckedUpdateManyInput>
  /**
   * Filter which Schools to update
   */
  where?: Prisma.SchoolWhereInput
  /**
   * Limit how many Schools to update.
   */
  limit?: number
}

/**
 * School updateManyAndReturn
 */
export type SchoolUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * The data used to update Schools.
   */
  data: Prisma.XOR<Prisma.SchoolUpdateManyMutationInput, Prisma.SchoolUncheckedUpdateManyInput>
  /**
   * Filter which Schools to update
   */
  where?: Prisma.SchoolWhereInput
  /**
   * Limit how many Schools to update.
   */
  limit?: number
}

/**
 * School upsert
 */
export type SchoolUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolInclude<ExtArgs> | null
  /**
   * The filter to search for the School to update in case it exists.
   */
  where: Prisma.SchoolWhereUniqueInput
  /**
   * In case the School found by the `where` argument doesn't exist, create a new School with this data.
   */
  create: Prisma.XOR<Prisma.SchoolCreateInput, Prisma.SchoolUncheckedCreateInput>
  /**
   * In case the School was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SchoolUpdateInput, Prisma.SchoolUncheckedUpdateInput>
}

/**
 * School delete
 */
export type SchoolDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolInclude<ExtArgs> | null
  /**
   * Filter which School to delete.
   */
  where: Prisma.SchoolWhereUniqueInput
}

/**
 * School deleteMany
 */
export type SchoolDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Schools to delete
   */
  where?: Prisma.SchoolWhereInput
  /**
   * Limit how many Schools to delete.
   */
  limit?: number
}

/**
 * School.schoolDetails
 */
export type School$schoolDetailsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDetails
   */
  select?: Prisma.SchoolDetailsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDetails
   */
  omit?: Prisma.SchoolDetailsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDetailsInclude<ExtArgs> | null
  where?: Prisma.SchoolDetailsWhereInput
}

/**
 * School without action
 */
export type SchoolDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the School
   */
  select?: Prisma.SchoolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the School
   */
  omit?: Prisma.SchoolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolInclude<ExtArgs> | null
}
